### PR TITLE
fix: bring device types in-line with API docs

### PR DESCRIPTION
**Pull request by rossiam**
Updated list of types to match current API docs.

### CODE REVIEW

**Comment by john-u** [comment]
~bug:~ fix: on the commit so that release is correct. I will make a ticket to install [commitlint](https://github.com/conventional-changelog/commitlint) for us.

**Comment by bflorian** [comment]
Looks good to me other than commit name John mentions

**Comment by rossiam** [comment]
> ~bug:~ fix: on the commit so that release is correct. I will make a ticket to install [commitlint](https://github.com/conventional-changelog/commitlint) for us.

Dang it...did that again. Fixed.

**Pull request merged**
